# Generated by Django 5.1.6 on 2025-08-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterviewquestion',
            name='audio_url',
            field=models.URLField(blank=True, help_text='URL to the audio file for this question', max_length=500, null=True),
        ),
    ]
