# Generated by Django 5.1.6 on 2025-07-29 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(db_index=True, max_length=255)),
                ("company_name", models.CharField(db_index=True, max_length=255)),
                ("spoc_email", models.EmailField(max_length=254)),
                ("hiring_manager_email", models.EmailField(max_length=254)),
                ("current_team_size_info", models.CharField(blank=True, max_length=50)),
                (
                    "number_to_hire",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "position_level",
                    models.CharField(
                        choices=[
                            ("IC", "Individual Contributor"),
                            ("Manager", "Manager"),
                        ],
                        max_length=50,
                    ),
                ),
                ("current_process", models.TextField(blank=True)),
                ("tech_stack_details", models.TextField()),
                (
                    "jd_file",
                    models.FileField(
                        blank=True, null=True, upload_to="job_descriptions/"
                    ),
                ),
                ("jd_link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
