# Generated by Django 5.1.6 on 2025-08-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_domain_job_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(blank=True, help_text='Detailed job description, responsibilities, requirements, etc.'),
        ),
    ]
