# Generated by Django 5.1.6 on 2025-07-22 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_delete_jobdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='current_team_size',
        ),
        migrations.AddField(
            model_name='job',
            name='current_team_size_info',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='number_to_hire',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
