# Generated by Django 5.1.6 on 2025-11-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='coding_language',
            field=models.CharField(choices=[('PYTHON', 'Python'), ('JAVASCRIPT', 'JavaScript'), ('JAVA', 'Java'), ('PHP', 'PHP'), ('RUBY', 'Ruby'), ('CSHARP', 'C#'), ('SQL', 'SQL')], default='PYTHON', help_text='Primary coding language for coding round interviews', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='tech_stack_details',
            field=models.TextField(blank=True, help_text='Legacy field - use coding_language instead'),
        ),
    ]
