# Generated by Django 5.1.6 on 2025-11-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_coding_language_alter_job_tech_stack_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='coding_language',
            field=models.CharField(choices=[('PYTHON', 'Python'), ('JAVASCRIPT', 'JavaScript'), ('C', 'C'), ('CPP', 'C++'), ('JAVA', 'Java'), ('GO', 'Go'), ('HTML', 'HTML'), ('PHP', 'PHP'), ('RUBY', 'Ruby'), ('CSHARP', 'C#'), ('SQL', 'SQL')], default='PYTHON', help_text='Primary coding language for coding round interviews', max_length=50),
        ),
    ]
