#!/usr/bin/env python
"""
Generate coding questions with test cases for an interview session
"""
import os
import django

# Setup Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'interview_app.settings')
django.setup()

from interview_app.models import InterviewSession, InterviewQuestion, TestCase
from interview_app.coding_service import generate_coding_questions_with_testcases


def generate_coding_for_session(session_key: str, num_questions: int = 2):
    """Generate coding questions with test cases for a session"""
    try:
        session = InterviewSession.objects.get(session_key=session_key)
        
        print(f"\n{'='*70}")
        print(f"Generating {num_questions} coding questions for session: {session_key}")
        print(f"Candidate: {session.candidate_name}")
        print(f"{'='*70}\n")
        
        # Get job description
        jd = session.job_description or "Software Developer position requiring Python, algorithms, and problem-solving skills."
        
        # Generate questions using Gemini
        print("🤖 Generating coding questions with Gemini AI...")
        questions_data = generate_coding_questions_with_testcases(jd, num_questions)
        
        # Ensure we got questions from Gemini
        if not questions_data:
            print("❌ No questions generated by Gemini!")
            print("Please check:")
            print("  1. Gemini API key is valid")
            print("  2. Internet connection is working")
            print("  3. Model name is correct")
            return False
        
        # Get the highest order number for existing questions
        existing_questions = InterviewQuestion.objects.filter(session=session).order_by('-order')
        next_order = (existing_questions.first().order + 1) if existing_questions.exists() else 0
        
        # Create questions in database
        for idx, q_data in enumerate(questions_data):
            print(f"\n📝 Creating Question {idx + 1}: {q_data['title']}")
            
            question = InterviewQuestion.objects.create(
                session=session,
                question_text=q_data['description'],
                question_type='CODING',
                coding_language=q_data['language'],
                order=next_order + idx
            )
            
            # Create test cases
            for tc_data in q_data.get('test_cases', []):
                TestCase.objects.create(
                    question=question,
                    input_data=tc_data['input'],
                    expected_output=tc_data['expected_output'],
                    is_hidden=False
                )
                print(f"   ✅ Test case: {tc_data['input']} → {tc_data['expected_output']}")
            
            print(f"   ✅ Created question with {len(q_data.get('test_cases', []))} test cases")
        
        print(f"\n{'='*70}")
        print(f"✅ Successfully created {len(questions_data)} coding questions!")
        print(f"{'='*70}\n")
        
        return True
        
    except InterviewSession.DoesNotExist:
        print(f"❌ Session not found: {session_key}")
        return False
    except Exception as e:
        print(f"❌ Error generating coding questions: {e}")
        import traceback
        traceback.print_exc()
        return False


if __name__ == '__main__':
    import sys
    
    if len(sys.argv) > 1:
        session_key = sys.argv[1]
        num_questions = int(sys.argv[2]) if len(sys.argv) > 2 else 2
    else:
        # Get the most recent session
        latest_session = InterviewSession.objects.filter(status='SCHEDULED').order_by('-created_at').first()
        if not latest_session:
            print("❌ No active sessions found")
            sys.exit(1)
        session_key = latest_session.session_key
        num_questions = 2
        print(f"Using latest session: {session_key}")
    
    generate_coding_for_session(session_key, num_questions)

