# Generated by Django 5.1.6 on 2025-07-31 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hiring_agency", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userdata",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userdata",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Company", "Company"),
                    ("Recruiter", "Recruiter"),
                    ("Hiring Agency", "Hiring Agency"),
                ],
                max_length=50,
            ),
        ),
    ]
