# Generated by Django 5.1.6 on 2025-07-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_agency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userdata',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Sourcing Partner', 'Sourcing Partner'), ('Recruiter', 'Recruiter')], max_length=50),
        ),
    ]
