# Generated by Django 5.1.6 on 2025-08-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hiring_agency", "0002_userdata_company_name_userdata_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
