# Generated by Django 5.1.6 on 2025-08-08 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_email_company_password'),
        ('hiring_agency', '0003_userdata_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_agencies', to='companies.company'),
        ),
    ]
