# Generated by Django 5.1.6 on 2025-09-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hiring_agency", "0005_populate_company_foreignkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
