# Generated by Django 5.1.6 on 2025-08-04 10:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional performance data')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_name', 'timestamp'], name='dashboard_s_metric__d39f63_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('resume_upload', 'Resume Uploads'), ('interview_scheduled', 'Interviews Scheduled'), ('interview_completed', 'Interviews Completed'), ('candidate_added', 'Candidates Added'), ('job_created', 'Jobs Created'), ('evaluation_completed', 'Evaluations Completed'), ('user_activity', 'User Activity'), ('system_performance', 'System Performance')], max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.IntegerField(default=0)),
                ('data', models.JSONField(default=dict, help_text='Additional metric data')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['metric_type', 'date'], name='dashboard_d_metric__bd06e2_idx'), models.Index(fields=['user', 'date'], name='dashboard_d_user_id_ce6d5b_idx'), models.Index(fields=['company_name', 'date'], name='dashboard_d_company_8875e5_idx')],
                'unique_together': {('metric_type', 'user', 'company_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('resume_stats', 'Resume Statistics'), ('interview_stats', 'Interview Statistics'), ('candidate_stats', 'Candidate Statistics'), ('job_stats', 'Job Statistics'), ('activity_chart', 'Activity Chart'), ('performance_metrics', 'Performance Metrics'), ('recent_activity', 'Recent Activity'), ('quick_actions', 'Quick Actions')], max_length=50)),
                ('position', models.IntegerField(default=0, help_text='Widget position on dashboard')),
                ('is_enabled', models.BooleanField(default=True)),
                ('settings', models.JSONField(default=dict, help_text='Widget-specific settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('user', 'widget_type')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('resume_upload', 'Resume Upload'), ('interview_schedule', 'Interview Schedule'), ('candidate_add', 'Candidate Addition'), ('job_create', 'Job Creation'), ('evaluation_submit', 'Evaluation Submit'), ('bulk_upload', 'Bulk Upload'), ('search', 'Search'), ('export', 'Data Export')], max_length=50)),
                ('details', models.JSONField(default=dict, help_text='Activity details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'activity_type', 'created_at'], name='dashboard_u_user_id_feee39_idx'), models.Index(fields=['activity_type', 'created_at'], name='dashboard_u_activit_5ca3c8_idx')],
            },
        ),
    ]
