# Generated by Django 5.1.6 on 2025-08-04 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('COMPANY', 'Company'), ('HIRING_AGENCY', 'Hiring Agency'), ('RECRUITER', 'Recruiter'), ('HR', 'HR'), ('TALENT_ACQUISITION', 'Talent Acquisition Specialist'), ('TECHNICAL_INTERVIEWER', 'Technical Interviewer'), ('TEAM_LEAD', 'Team Lead'), ('DEPARTMENT_HEAD', 'Department Head'), ('PROJECT_MANAGER', 'Project Manager'), ('CTO', 'CTO'), ('OTHERS', 'Others')], default='OTHERS', max_length=50),
        ),
    ]
