# Generated by Django 5.1.6 on 2025-07-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('HIRING_MANAGER', 'Hiring Manager'), ('RECRUITER', 'Recruiter'), ('TALENT_ACQUISITION', 'Talent Acquisition Specialist'), ('TECHNICAL_INTERVIEWER', 'Technical Interviewer'), ('TEAM_LEAD', 'Team Lead'), ('DEPARTMENT_HEAD', 'Department Head'), ('PROJECT_MANAGER', 'Project Manager'), ('CTO', 'CTO'), ('ADMIN', 'Admin'), ('COMPANY', 'Company'), ('OTHERS', 'Others')], default='OTHERS', max_length=50),
        ),
    ]
