# Generated by Django 5.1.6 on 2025-12-05 11:09

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_initial_admin_user(apps, schema_editor):
    """
    Create initial admin user if it doesn't exist.
    This will run automatically when migrations are applied.
    """
    User = apps.get_model("authapp", "CustomUser")
    
    # Admin user credentials
    admin_email = "admin@rslsolution.com"
    admin_password = "admin123456"
    admin_full_name = "Admin User"
    
    # Check if admin user already exists
    if not User.objects.filter(email=admin_email).exists():
        # Create admin user
        # Note: In migrations, we need to hash the password manually
        # because the historical model doesn't have set_password() method
        admin_user = User.objects.create(
            username=admin_email,
            email=admin_email,
            full_name=admin_full_name,
            role="ADMIN",  # Use string value directly (Role is TextChoices, not a model)
            password=make_password(admin_password),  # Hash password directly
            is_staff=True,
            is_superuser=True,
            is_active=True,
        )
        print(f"✅ Created admin user: {admin_email}")
    else:
        print(f"ℹ️  Admin user already exists: {admin_email}")


def reverse_create_initial_admin_user(apps, schema_editor):
    """
    Reverse migration: Delete the admin user (optional, for rollback)
    """
    User = apps.get_model("authapp", "CustomUser")
    admin_email = "admin@rslsolution.com"
    
    User.objects.filter(email=admin_email).delete()
    print(f"🗑️  Deleted admin user: {admin_email}")


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_customuser_company_alter_customuser_role'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_admin_user,
            reverse_create_initial_admin_user
        ),
    ]
