# Generated by Django 5.1.6 on 2025-07-29 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('work_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=100)),
                ('poc_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REQUIRES_ACTION', 'Requires Action'), ('PENDING_SCHEDULING', 'Pending Scheduling'), ('BR_IN_PROCESS', 'BR In Process'), ('BR_EVALUATED', 'BR Evaluated'), ('INTERNAL_INTERVIEWS', 'Internal Interviews'), ('OFFERED', 'Offered'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('OFFER_REJECTED', 'Offer Rejected'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=40)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='jobs.job')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='resumes.resume')),
            ],
        ),
    ]
