# Generated by Django 5.1.6 on 2025-08-04 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Domain/technology area', max_length=100)),
                ('role', models.CharField(help_text='Job role/position', max_length=100)),
                ('resume_file', models.FileField(help_text='Uploaded resume file', upload_to='candidate_drafts/')),
                ('extracted_data', models.JSONField(default=dict, help_text='Data extracted from resume')),
                ('verified_data', models.JSONField(default=dict, help_text='User-verified data')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('extracted', 'Data Extracted'), ('verified', 'Verified'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
