# Generated by Django 5.1.6 on 2025-08-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidatedraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='domain',
            field=models.CharField(blank=True, help_text='Domain/technology area', max_length=100),
        ),
    ]
