# Generated by Django 5.1.6 on 2025-07-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='job',
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
