# Generated by Django 5.1.6 on 2025-08-06 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0003_alter_candidate_domain"),
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="resume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="resumes.resume",
            ),
        ),
    ]
