# Generated by Django 5.1.6 on 2025-09-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0004_alter_candidate_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("INTERVIEW_SCHEDULED", "Interview Scheduled"),
                    ("INTERVIEW_COMPLETED", "Interview Completed"),
                    ("EVALUATED", "Evaluated"),
                    ("REQUIRES_ACTION", "Requires Action"),
                    ("PENDING_SCHEDULING", "Pending Scheduling"),
                    ("BR_IN_PROCESS", "BR In Process"),
                    ("BR_EVALUATED", "BR Evaluated"),
                    ("INTERNAL_INTERVIEWS", "Internal Interviews"),
                    ("OFFERED", "Offered"),
                    ("HIRED", "Hired"),
                    ("REJECTED", "Rejected"),
                    ("OFFER_REJECTED", "Offer Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="NEW",
                max_length=40,
            ),
        ),
    ]
