# Generated by Django 5.1.6 on 2026-02-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_alter_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='education_match',
            field=models.FloatField(blank=True, help_text='Education match percentage (calculated by Gemini AI)', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_match',
            field=models.FloatField(blank=True, help_text='Experience match percentage (calculated by Gemini AI)', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='match_percentage',
            field=models.FloatField(blank=True, help_text='Overall match percentage with job description (calculated by Gemini AI)', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='relevance_score',
            field=models.FloatField(blank=True, help_text='Relevance score (calculated by Gemini AI)', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Comprehensive resume analysis from Gemini AI'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skill_match',
            field=models.FloatField(blank=True, help_text='Skill match percentage (calculated by Gemini AI)', null=True),
        ),
    ]
