# Generated by Django 5.1.6 on 2025-08-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0003_auto_20250822_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='recording_created_at',
            field=models.DateTimeField(blank=True, help_text='When the recording was created', null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='recording_video',
            field=models.FileField(blank=True, help_text='Recorded video of the interview session', null=True, upload_to='interview_recordings/'),
        ),
    ]
