# Generated by Django 5.1.6 on 2025-08-22 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesubmission',
            name='question',
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='question_id',
            field=models.CharField(default=django.utils.timezone.now, help_text='Question ID (can be UUID or integer)', max_length=36),
            preserve_default=False,
        ),
    ]
