# Generated by Django 5.1.6 on 2025-08-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0002_remove_codesubmission_question_and_more'),
    ]

    operations = [
    ]
