# Generated by Django 5.1.6 on 2025-11-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0005_warninglog_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='conversation_sequence',
            field=models.PositiveIntegerField(blank=True, help_text='Sequential index for conversation flow', null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='role',
            field=models.CharField(blank=True, help_text='Role: AI or INTERVIEWEE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='coding_language',
            field=models.CharField(blank=True, choices=[('PYTHON', 'Python'), ('JAVASCRIPT', 'JavaScript'), ('JAVA', 'Java'), ('C', 'C'), ('CPP', 'C++'), ('GO', 'Go'), ('HTML', 'HTML'), ('PHP', 'PHP'), ('RUBY', 'Ruby'), ('CSHARP', 'C#'), ('SQL', 'SQL')], max_length=20, null=True),
        ),
    ]
