# Generated by Django 5.1.6 on 2025-11-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0006_interviewquestion_conversation_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='interview_video',
            field=models.FileField(blank=True, help_text='Complete interview video with camera, TTS questions, and candidate speech', null=True, upload_to='interview_videos/'),
        ),
    ]
