# Generated by Django 5.1.6 on 2025-12-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0007_interviewsession_interview_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='warninglog',
            name='snapshot_image',
            field=models.ImageField(blank=True, help_text='Snapshot image stored in database', null=True, upload_to='proctoring_snaps/'),
        ),
    ]
