# Generated by Django 5.1.6 on 2026-01-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0009_fix_question_level_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='question_level',
            field=models.CharField(default='MAIN', max_length=10),
        ),
    ]
