# Generated by Django 5.1.6 on 2025-12-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0009_fix_question_level_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='video_gcs_url',
            field=models.URLField(blank=True, help_text='Google Cloud Storage URL for the interview video', max_length=500, null=True),
        ),
    ]

