# Generated by Django 5.1.6 on 2025-12-23 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0010_add_video_gcs_url'),
        ('interviews', '0009_alter_interviewslot_duration_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(help_text='Sequential question number (1, 2, 3...)')),
                ('question_text', models.TextField(help_text='The question asked to the candidate')),
                ('question_type', models.CharField(choices=[('INTRODUCTION', 'Introduction'), ('TECHNICAL', 'Technical'), ('BEHAVIORAL', 'Behavioral'), ('CODING', 'Coding Challenge')], default='TECHNICAL', max_length=50)),
                ('answer_text', models.TextField(blank=True, help_text="Candidate's transcribed answer", null=True)),
                ('transcribed_answer', models.TextField(blank=True, help_text='Alternative field for transcribed answer', null=True)),
                ('order', models.PositiveIntegerField(help_text='Order in sequence (same as question_number)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_time_seconds', models.FloatField(blank=True, null=True)),
                ('words_per_minute', models.IntegerField(blank=True, null=True)),
                ('filler_word_count', models.IntegerField(blank=True, null=True)),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_qa', to='interviews.interview')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_qa', to='interview_app.interviewsession')),
            ],
            options={
                'ordering': ['question_number', 'order'],
                'indexes': [models.Index(fields=['session', 'question_number'], name='interview_a_session_46a73c_idx'), models.Index(fields=['interview', 'question_number'], name='interview_a_intervi_5d67e3_idx')],
                'unique_together': {('session', 'question_number')},
            },
        ),
    ]
