# Generated by Django 5.1.6 on 2026-02-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0010_alter_interviewquestion_question_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='coding_round_completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when coding round was completed', null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='technical_interview_started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when technical interview started', null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='total_completion_time_minutes',
            field=models.FloatField(blank=True, help_text='Total time from technical interview start to coding round completion (in minutes)', null=True),
        ),
    ]
