# Generated by Django 5.1.6 on 2026-02-05 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0011_add_timing_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewquestion',
            options={'ordering': ['order', 'conversation_sequence']},
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='answered_at',
            field=models.DateTimeField(blank=True, help_text='When the answer was received', null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='asked_at',
            field=models.DateTimeField(blank=True, help_text='When the question was asked', null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='is_follow_up',
            field=models.BooleanField(default=False, help_text='Whether this is a follow-up question'),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='question_category',
            field=models.CharField(blank=True, help_text="Category of the question (e.g., 'algorithms', 'communication')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='coding_language',
            field=models.CharField(blank=True, choices=[('PYTHON', 'Python'), ('JAVASCRIPT', 'JavaScript'), ('JAVA', 'Java'), ('C', 'C'), ('CPP', 'C++'), ('GO', 'Go'), ('HTML', 'HTML'), ('PHP', 'PHP'), ('RUBY', 'Ruby'), ('CSHARP', 'C#'), ('SQL', 'SQL')], help_text='Programming language for coding questions', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='order',
            field=models.PositiveIntegerField(help_text='Question order in the interview'),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='question_level',
            field=models.CharField(choices=[('INTRO', 'Introduction'), ('MAIN', 'Main'), ('FOLLOWUP', 'Follow-up'), ('PRECLOSE', 'Pre-close'), ('CLOSE', 'Close')], default='MAIN', max_length=10),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='question_type',
            field=models.CharField(choices=[('INTRODUCTION', 'Introduction'), ('TECHNICAL', 'Technical'), ('BEHAVIORAL', 'Behavioral'), ('CODING', 'Coding Challenge'), ('PRECLOSING', 'Pre-closing'), ('CLOSING', 'Closing')], default='TECHNICAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='role',
            field=models.CharField(choices=[('AI', 'AI Interviewer'), ('INTERVIEWEE', 'Interviewee')], default='AI', help_text='Role: AI or INTERVIEWEE', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='transcribed_answer',
            field=models.TextField(blank=True, help_text='Transcribed answer from interviewee', null=True),
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['session', 'order'], name='interview_a_session_55895a_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['session', 'question_type'], name='interview_a_session_40ebe6_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['conversation_sequence'], name='interview_a_convers_4d7732_idx'),
        ),
    ]
