# Generated by Django 5.1.6 on 2026-02-17 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0011_add_timing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='coding_language',
            field=models.CharField(blank=True, choices=[('PYTHON', 'Python'), ('JAVASCRIPT', 'JavaScript'), ('JAVA', 'Java'), ('C', 'C'), ('CPP', 'C++'), ('GO', 'Go'), ('HTML', 'HTML'), ('PHP', 'PHP'), ('RUBY', 'Ruby'), ('CSHARP', 'C#'), ('SQL', 'SQL'), ('SWIFT', 'Swift')], max_length=20, null=True),
        ),
    ]
