# Generated by Django 5.1.6 on 2026-02-18 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0012_interviewquestion_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalInterviewQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_qa', models.TextField(help_text="Stores the full QA interaction in a single continuous format: 'AI Interviewer: <Q> | Interviewee: <A>'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_qa', to='interview_app.interviewsession')),
            ],
        ),
    ]
