# Generated by Django 5.1.6 on 2026-02-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0013_technicalinterviewqa'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='screen_recording',
            field=models.FileField(blank=True, help_text='Screen recording of the candidate during the interview', null=True, upload_to='screen_recordings/'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='screen_recording_gcs_url',
            field=models.URLField(blank=True, help_text='Google Cloud Storage URL for the screen recording', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='video_gcs_url',
            field=models.URLField(blank=True, help_text='Google Cloud Storage URL for the interview video', max_length=500, null=True),
        ),
    ]
