# Generated by Django 5.1.6 on 2026-03-04 05:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0014_interviewsession_screen_recording_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAConversationPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField(help_text='Question asked by AI (introductory, technical, follow-up, or clarification)')),
                ('answer_text', models.TextField(help_text='Answer given by candidate or question asked by candidate')),
                ('question_type', models.CharField(choices=[('INTRODUCTORY', 'Introductory'), ('TECHNICAL', 'Technical'), ('FOLLOW_UP', 'Follow-up'), ('CLARIFICATION', 'Clarification'), ('CANDIDATE_QUESTION', 'Candidate Question'), ('ELABORATION_REQUEST', 'Elaboration Request')], default='TECHNICAL', max_length=20)),
                ('question_number', models.PositiveIntegerField(help_text='Sequential number of the question in the interview')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_time_seconds', models.FloatField(blank=True, help_text='Time taken to respond in seconds', null=True)),
                ('words_per_minute', models.FloatField(blank=True, help_text='Speaking rate calculated from answer', null=True)),
                ('filler_word_count', models.PositiveIntegerField(default=0, help_text='Count of filler words in answer')),
                ('sentiment_score', models.FloatField(blank=True, help_text='Sentiment analysis score of the answer', null=True)),
                ('llm_analysis', models.TextField(blank=True, help_text='Gemini analysis of this Q&A pair', null=True)),
                ('llm_score', models.FloatField(blank=True, help_text='Score given by LLM for this Q&A', null=True)),
                ('analysis_timestamp', models.DateTimeField(blank=True, help_text='When LLM analysis was performed', null=True)),
                ('included_in_pdf', models.BooleanField(default=True, help_text='Whether this Q&A should be included in PDF report')),
                ('pdf_display_order', models.PositiveIntegerField(default=0, help_text='Order for displaying in PDF')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_conversation_pairs', to='interview_app.interviewsession')),
            ],
            options={
                'ordering': ['question_number', 'timestamp'],
                'indexes': [models.Index(fields=['session', 'question_number'], name='interview_a_session_eeaf50_idx'), models.Index(fields=['session', 'question_type'], name='interview_a_session_85ce21_idx')],
            },
        ),
    ]
