# Generated by Django 5.1.6 on 2026-03-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0015_qaconversationpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaconversationpair',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Session key for easy identification and filtering', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='qaconversationpair',
            index=models.Index(fields=['session_key'], name='interview_a_session_c053d8_idx'),
        ),
    ]
