# Generated by Django 5.1.6 on 2026-03-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0016_add_session_key_to_qa_conversation_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaconversationpair',
            name='question_number',
            field=models.IntegerField(help_text='Sequential number of the question in the interview (positive for AI questions, negative for candidate questions)'),
        ),
    ]
