# Generated by Django 5.1.6 on 2026-03-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0012_alter_interviewquestion_options_and_more'),
        ('interview_app', '0017_allow_negative_question_numbers'),
    ]

    operations = [
    ]
