# Generated by Django 5.1.6 on 2026-03-19 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0018_merge_20260305_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestion',
            name='answered_at',
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='asked_at',
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='is_follow_up',
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='question_category',
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='voice_analysis_pdf',
            field=models.FileField(blank=True, help_text='Voice analysis PDF report', null=True, upload_to='voice_analysis_reports/'),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='coding_language',
            field=models.CharField(blank=True, choices=[('PYTHON', 'Python'), ('JAVASCRIPT', 'JavaScript'), ('JAVA', 'Java'), ('C', 'C'), ('CPP', 'C++'), ('GO', 'Go'), ('HTML', 'HTML'), ('PHP', 'PHP'), ('RUBY', 'Ruby'), ('CSHARP', 'C#'), ('SQL', 'SQL'), ('SWIFT', 'Swift')], help_text='Programming language for coding questions', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='screen_recording_gcs_url',
            field=models.URLField(blank=True, help_text='Google Cloud Storage URL for screen recording', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='InterviewQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(help_text='Sequential question number (1, 2, 3...)')),
                ('question_text', models.TextField(help_text='The question asked by AI')),
                ('answer_text', models.TextField(blank=True, help_text="Candidate's answer to the question", null=True)),
                ('question_type', models.CharField(choices=[('INTRODUCTION', 'Introduction'), ('TECHNICAL', 'Technical'), ('BEHAVIORAL', 'Behavioral'), ('CODING', 'Coding'), ('CLOSING', 'Closing')], default='TECHNICAL', max_length=20)),
                ('audio_url', models.URLField(blank=True, help_text='Audio file for the question', max_length=500, null=True)),
                ('asked_at', models.DateTimeField(blank=True, help_text='When question was asked', null=True)),
                ('answered_at', models.DateTimeField(blank=True, help_text='When answer was received', null=True)),
                ('response_time_seconds', models.FloatField(blank=True, help_text='Time taken to answer in seconds', null=True)),
                ('words_per_minute', models.IntegerField(blank=True, help_text='Speaking rate calculation', null=True)),
                ('filler_word_count', models.IntegerField(blank=True, help_text='Filler words detected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_pairs', to='interview_app.interviewsession')),
            ],
            options={
                'ordering': ['question_number'],
                'indexes': [models.Index(fields=['session', 'question_number'], name='interview_a_session_a99c8f_idx')],
            },
        ),
    ]
