# Generated by Django 5.1.6 on 2026-03-19 06:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0019_remove_interviewquestion_answered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerVoiceAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_number', models.IntegerField(help_text='Answer number in the interview')),
                ('segment_start_time', models.FloatField(help_text='Start time of answer segment in seconds')),
                ('segment_end_time', models.FloatField(help_text='End time of answer segment in seconds')),
                ('segment_duration', models.FloatField(help_text='Duration of answer segment in seconds')),
                ('speech_percentage', models.FloatField(help_text='Percentage of segment with speech')),
                ('silence_percentage', models.FloatField(help_text='Percentage of segment with silence')),
                ('words_per_minute', models.FloatField(help_text='Speaking rate in words per minute')),
                ('filler_word_count', models.IntegerField(help_text='Number of filler words detected')),
                ('response_delay_seconds', models.FloatField(help_text='Delay before starting response')),
                ('multiple_speakers_detected', models.BooleanField(default=False, help_text='Multiple speakers detected in answer')),
                ('speaker_confidence_score', models.FloatField(help_text='Confidence score for speaker identification')),
                ('audio_quality_score', models.FloatField(help_text='Overall audio quality score')),
                ('insights', models.JSONField(default=dict, help_text='Detailed insights about the answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_analyses', to='interview_app.interviewquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_analyses', to='interview_app.interviewsession')),
            ],
            options={
                'ordering': ['answer_number'],
                'indexes': [models.Index(fields=['session', 'answer_number'], name='interview_a_session_2efb00_idx'), models.Index(fields=['created_at'], name='interview_a_created_5bfdd8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpeakerDiarization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker_changes', models.IntegerField(help_text='Number of speaker changes detected')),
                ('speaker_change_timestamps', models.JSONField(default=list, help_text='Timestamps when speaker changes occurred')),
                ('num_speakers', models.IntegerField(help_text='Number of distinct speakers detected')),
                ('speaker_labels', models.JSONField(default=dict, help_text='Speaker label information')),
                ('candidate_speech_percentage', models.FloatField(help_text='Percentage of time candidate spoke')),
                ('interviewer_speech_percentage', models.FloatField(help_text='Percentage of time interviewer spoke')),
                ('diarization_segments', models.JSONField(default=list, help_text='Raw diarization segment data')),
                ('analysis_start_time', models.DateTimeField(auto_now_add=True)),
                ('analysis_end_time', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_diarizations', to='interview_app.interviewquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_diarizations', to='interview_app.interviewsession')),
            ],
            options={
                'ordering': ['analysis_start_time'],
                'indexes': [models.Index(fields=['session', 'question'], name='interview_a_session_8a7cef_idx'), models.Index(fields=['analysis_start_time'], name='interview_a_analysi_21936f_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoiceActivityDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pause_duration', models.FloatField(help_text='Total pause duration in seconds')),
                ('total_speech_time', models.FloatField(help_text='Total speech time in seconds')),
                ('speech_percentage', models.FloatField(help_text='Percentage of time spent speaking')),
                ('silence_percentage', models.FloatField(help_text='Percentage of time spent in silence')),
                ('response_delay_start', models.DateTimeField(blank=True, help_text='When question ended', null=True)),
                ('response_delay_end', models.DateTimeField(blank=True, help_text='When candidate started responding', null=True)),
                ('response_delay_seconds', models.FloatField(blank=True, help_text='Response delay in seconds', null=True)),
                ('vad_segments', models.JSONField(default=list, help_text='Raw VAD segment data')),
                ('analysis_start_time', models.DateTimeField(auto_now_add=True)),
                ('analysis_end_time', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_activities', to='interview_app.interviewquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_activities', to='interview_app.interviewsession')),
            ],
            options={
                'ordering': ['analysis_start_time'],
                'indexes': [models.Index(fields=['session', 'question'], name='interview_a_session_d89673_idx'), models.Index(fields=['analysis_start_time'], name='interview_a_analysi_f99e18_idx')],
            },
        ),
    ]
