# Generated by Django 5.1.6 on 2026-03-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0020_add_voice_analysis_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='voice_analysis_pdf',
            field=models.FileField(blank=True, help_text='Voice analysis PDF report', null=True, upload_to='voice_analysis_reports/'),
        ),
    ]
