# Generated by Django 5.1.6 on 2026-04-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0021_add_voice_analysis_pdf_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='interview_video',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='resume_feedback',
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='screen_recording',
            field=models.FileField(blank=True, help_text='Screen recording of candidate during the interview', null=True, upload_to='screen_recordings/'),
        ),
    ]
