# Generated by Django 5.1.6 on 2025-08-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="company",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
