# Generated by Django 5.1.6 on 2025-08-11 08:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_email_company_password"),
        ("interviews", "0001_initial"),
        ("jobs", "0002_domain_job_domain"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewConflict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("overlap", "Time Overlap"),
                            ("interviewer_unavailable", "Interviewer Unavailable"),
                            ("candidate_unavailable", "Candidate Unavailable"),
                            ("system_error", "System Error"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Resolution"),
                            ("rescheduled", "Rescheduled"),
                            ("cancelled", "Cancelled"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("conflict_details", models.JSONField(default=dict)),
                ("resolution_notes", models.TextField(blank=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conflicting_interview",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicting_interviews",
                        to="interviews.interview",
                    ),
                ),
                (
                    "primary_interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_conflicts",
                        to="interviews.interview",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Time Slot"),
                            ("flexible", "Flexible Time Slot"),
                            ("recurring", "Recurring Slot"),
                        ],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("booked", "Booked"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60, help_text="Duration in minutes"
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurring_pattern",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Recurring pattern configuration",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "max_candidates",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum candidates per slot"
                    ),
                ),
                ("current_bookings", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_slots",
                        to="companies.company",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        limit_choices_to={
                            "role__in": [
                                "ADMIN",
                                "COMPANY",
                                "HIRING_AGENCY",
                                "RECRUITER",
                            ]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_slots",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="InterviewSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("booking_notes", models.TextField(blank=True)),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interview",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="interviews.interview",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="interviews.interviewslot",
                    ),
                ),
            ],
            options={
                "ordering": ["-booked_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewerAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "slot_duration",
                    models.PositiveIntegerField(
                        default=60, help_text="Duration in minutes"
                    ),
                ),
                (
                    "break_duration",
                    models.PositiveIntegerField(
                        default=15, help_text="Break between slots in minutes"
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("max_slots_per_day", models.PositiveIntegerField(default=8)),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviewer_availability",
                        to="companies.company",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_patterns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week", "start_time"],
                "unique_together": {("interviewer", "day_of_week", "valid_from")},
            },
        ),
        migrations.AddIndex(
            model_name="interviewslot",
            index=models.Index(
                fields=["start_time", "end_time"], name="interviews__start_t_d868b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewslot",
            index=models.Index(
                fields=["interviewer", "start_time"],
                name="interviews__intervi_1df180_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interviewslot",
            index=models.Index(
                fields=["company", "start_time"], name="interviews__company_8820c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewslot",
            index=models.Index(
                fields=["status", "start_time"], name="interviews__status_363eb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewschedule",
            index=models.Index(
                fields=["status", "booked_at"], name="interviews__status_7fdee1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewschedule",
            index=models.Index(
                fields=["slot", "status"], name="interviews__slot_id_b0c9c8_idx"
            ),
        ),
    ]
