# Generated by Django 5.1.6 on 2025-08-11 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_email_company_password'),
        ('interviews', '0002_interviewconflict_interviewslot_interviewschedule_and_more'),
        ('jobs', '0002_domain_job_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInterviewConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('technical', 'Technical Interview'), ('behavioral', 'Behavioral Interview'), ('coding', 'Coding Interview'), ('system_design', 'System Design Interview'), ('general', 'General Interview')], max_length=20)),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration', models.PositiveIntegerField(default=60, help_text='Duration in minutes')),
                ('break_duration', models.PositiveIntegerField(default=15, help_text='Break between slots in minutes')),
                ('ai_settings', models.JSONField(default=dict, help_text='AI interview specific settings')),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='intervieweravailability',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='intervieweravailability',
            name='company',
        ),
        migrations.RemoveField(
            model_name='intervieweravailability',
            name='interviewer',
        ),
        migrations.RemoveIndex(
            model_name='interviewslot',
            name='interviews__intervi_1df180_idx',
        ),
        migrations.RemoveField(
            model_name='interviewslot',
            name='interviewer',
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='ai_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='AI interview configuration settings'),
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='ai_interview_type',
            field=models.CharField(choices=[('technical', 'Technical Interview'), ('behavioral', 'Behavioral Interview'), ('coding', 'Coding Interview'), ('system_design', 'System Design Interview'), ('general', 'General Interview')], default='general', help_text='Type of AI interview to be conducted', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewconflict',
            name='conflict_type',
            field=models.CharField(choices=[('overlap', 'Time Overlap'), ('ai_system_error', 'AI System Error'), ('slot_unavailable', 'Slot Unavailable'), ('candidate_unavailable', 'Candidate Unavailable'), ('system_error', 'System Error')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='interviewslot',
            index=models.Index(fields=['ai_interview_type', 'start_time'], name='interviews__ai_inte_87dfbe_idx'),
        ),
        migrations.AddField(
            model_name='aiinterviewconfiguration',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interview_configurations', to='companies.company'),
        ),
        migrations.DeleteModel(
            name='InterviewerAvailability',
        ),
        migrations.AlterUniqueTogether(
            name='aiinterviewconfiguration',
            unique_together={('company', 'interview_type', 'day_of_week', 'valid_from')},
        ),
    ]
