# Generated by Django 5.1.6 on 2025-08-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_email_company_password"),
        ("interviews", "0003_aiinterviewconfiguration_and_more"),
        ("jobs", "0002_domain_job_domain"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="interviewslot",
            name="interviews__status_363eb9_idx",
        ),
        migrations.RemoveIndex(
            model_name="interviewslot",
            name="interviews__ai_inte_87dfbe_idx",
        ),
        migrations.AddField(
            model_name="interview",
            name="interview_link",
            field=models.CharField(
                blank=True,
                help_text="Secure link for candidate to join interview",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="link_expires_at",
            field=models.DateTimeField(
                blank=True, help_text="When the interview link expires", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="interviewslot",
            index=models.Index(
                fields=["status", "ai_interview_type"],
                name="interviews__status_6ee7e5_idx",
            ),
        ),
    ]
