# Generated by Django 5.1.6 on 2025-08-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_fix_interview_link_length'),
        ('interviews', '0004_remove_interviewslot_interviews__status_363eb9_idx_and_more'),
    ]

    operations = [
    ]
