# Generated by Django 5.1.6 on 2025-08-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0005_merge_20250814_1855"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="session_key",
            field=models.CharField(
                blank=True,
                help_text="Short session key for AI interview portal access",
                max_length=40,
            ),
        ),
    ]
