# Generated by Django 5.1.6 on 2025-09-18 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_email_company_password"),
        ("interviews", "0006_interview_session_key"),
        ("jobs", "0003_job_job_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interviewslot",
            options={"ordering": ["interview_date", "start_time"]},
        ),
        migrations.RemoveIndex(
            model_name="interviewslot",
            name="interviews__start_t_d868b1_idx",
        ),
        migrations.RemoveIndex(
            model_name="interviewslot",
            name="interviews__company_8820c7_idx",
        ),
        migrations.AddField(
            model_name="interviewslot",
            name="interview_date",
            field=models.DateField(
                default=datetime.date.today, help_text="Date of the interview"
            ),
        ),
        migrations.AddField(
            model_name="interviewslot",
            name="legacy_end_datetime",
            field=models.DateTimeField(
                blank=True, help_text="Legacy combined datetime field", null=True
            ),
        ),
        migrations.AddField(
            model_name="interviewslot",
            name="legacy_start_datetime",
            field=models.DateTimeField(
                blank=True, help_text="Legacy combined datetime field", null=True
            ),
        ),
        migrations.AlterField(
            model_name="interviewslot",
            name="end_time",
            field=models.TimeField(
                default=datetime.time(10, 0), help_text="End time in 24-hour format"
            ),
        ),
        migrations.AlterField(
            model_name="interviewslot",
            name="start_time",
            field=models.TimeField(
                default=datetime.time(9, 0), help_text="Start time in 24-hour format"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewslot",
            index=models.Index(
                fields=["interview_date", "start_time"],
                name="interviews__intervi_a0e9c7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interviewslot",
            index=models.Index(
                fields=["company", "interview_date"],
                name="interviews__company_3f2bee_idx",
            ),
        ),
    ]
