# Generated by Django 5.1.6 on 2025-09-23 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0004_alter_candidate_resume"),
        ("interviews", "0007_separate_date_time_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviews",
                to="interviews.interviewslot",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="interview",
            unique_together={("candidate", "slot")},
        ),
    ]
