# Generated by Django 5.1.6 on 2025-11-05 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_interview_slot_alter_interview_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewslot',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='interviewslot',
            name='end_time',
            field=models.TimeField(default=datetime.time(8, 10), help_text='End time in 24-hour format'),
        ),
        migrations.AlterField(
            model_name='interviewslot',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Start time in 24-hour format'),
        ),
    ]
