# Generated by Django 5.1.6 on 2026-02-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0011_add_scheduled_time_to_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='screen_recording_duration',
            field=models.IntegerField(blank=True, help_text='Duration of screen recording in seconds', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='screen_recording_file',
            field=models.FileField(blank=True, help_text='Screen recording video file with audio', null=True, upload_to='screen_recordings/'),
        ),
        migrations.AddField(
            model_name='interview',
            name='screen_recording_url',
            field=models.URLField(blank=True, help_text='URL to screen recording with audio', max_length=500),
        ),
    ]
