# Generated by Django 5.1.6 on 2025-08-04 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("interview_scheduled", "Interview Scheduled"),
                            ("interview_reminder", "Interview Reminder"),
                            ("resume_processed", "Resume Processed"),
                            ("candidate_added", "Candidate Added"),
                            ("job_created", "Job Created"),
                            ("evaluation_completed", "Evaluation Completed"),
                            ("system_alert", "System Alert"),
                            ("permission_granted", "Permission Granted"),
                            ("bulk_upload_completed", "Bulk Upload Completed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "title_template",
                    models.CharField(
                        help_text="Template for notification title", max_length=255
                    ),
                ),
                (
                    "message_template",
                    models.TextField(help_text="Template for notification message"),
                ),
                (
                    "channels",
                    models.JSONField(
                        default=list, help_text="Default channels for this template"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("interview_notifications", models.BooleanField(default=True)),
                ("resume_notifications", models.BooleanField(default=True)),
                ("system_notifications", models.BooleanField(default=True)),
                ("daily_digest", models.BooleanField(default=False)),
                ("weekly_summary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("interview_scheduled", "Interview Scheduled"),
                            ("interview_reminder", "Interview Reminder"),
                            ("resume_processed", "Resume Processed"),
                            ("candidate_added", "Candidate Added"),
                            ("job_created", "Job Created"),
                            ("evaluation_completed", "Evaluation Completed"),
                            ("system_alert", "System Alert"),
                            ("permission_granted", "Permission Granted"),
                            ("bulk_upload_completed", "Bulk Upload Completed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("read", "Read"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        default=list,
                        help_text="List of channels to send notification through",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional data for the notification"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("email_sent", models.BooleanField(default=False)),
                ("in_app_sent", models.BooleanField(default=False)),
                ("sms_sent", models.BooleanField(default=False)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "status"],
                        name="notificatio_recipie_e285de_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "created_at"],
                        name="notificatio_notific_f2e0f7_idx",
                    ),
                    models.Index(
                        fields=["priority", "status"],
                        name="notificatio_priorit_27f109_idx",
                    ),
                ],
            },
        ),
    ]
